//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public System.Guid idcustomers { get; set; }
        public string name { get; set; }
        public string publicAddress { get; set; }
        public string privateAddress { get; set; }
        public string phone { get; set; }
        public Nullable<System.Guid> district { get; set; }
    }
}
