//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmployees
{
	using System;
	using System.Collections.Generic;

	public partial class districtsmasters
	{
		public System.Guid master { get; set; }
		public System.Guid district { get; set; }
		public int priority { get; set; }
	}
}
