//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class masters
    {
        public System.Guid idMasters { get; set; }
        public string email { get; set; }
        public string nameInMail { get; set; }
        public string name { get; set; }
        public string IdFirebase { get; set; }
        public Nullable<int> deposit { get; set; }
    }
}
