//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public System.Guid idOrders { get; set; }
        public System.Guid Customer { get; set; }
        public System.Guid Work { get; set; }
        public int InitialAmount { get; set; }
        public string CustomerComment { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string MasterComment { get; set; }
        public Nullable<System.DateTime> formationDate { get; set; }
        public Nullable<System.DateTime> takenDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.Guid> Master { get; set; }
        public Nullable<System.Guid> District { get; set; }
        public string orderNumber { get; set; }
        public Nullable<System.Guid> workType { get; set; }
        public bool masterArrived { get; set; }
    }
}
