//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEmployees
{
    using System;
    using System.Collections.Generic;
    
    public partial class worktypesmasters
    {
        public System.Guid worktype { get; set; }
        public System.Guid master { get; set; }
    }
}
